// Syncs data/products.ts from the product Google Sheet.
// Run: npm run sync:products
//
// After running, the file change still needs to be committed/pushed and a new
// deploy triggered (Vercel doesn't redeploy on its own just because the Sheet changed) —
// this script only regenerates the local static data file.

import fs from 'node:fs';
import path from 'node:path';
import Papa from 'papaparse';

const SHEET_ID = '1CF4WiaLIKKOCofgZJrJM5m8kpcKwpJjJcxrBsQFE5So';
const CSV_URL = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=0`;

const PLACEMENT_MAP: Record<string, 'tossing' | 'result' | 'both'> = {
  'Gieo quẻ': 'tossing',
  'Kết quả': 'result',
  'Cả hai': 'both',
};

interface SheetRow {
  'Tên'?: string;
  'Tóm tắt công dụng'?: string;
  'Image'?: string;
  'Affiliate link'?: string;
  'Vị trí hiển thị'?: string;
}

interface Product {
  name: string;
  summary?: string;
  image: string;
  affiliateLink: string;
  placement: 'tossing' | 'result' | 'both';
}

async function fetchSheetRows(): Promise<SheetRow[]> {
  const res = await fetch(CSV_URL);
  if (!res.ok) {
    throw new Error(`Failed to fetch the Google Sheet (HTTP ${res.status}). Is it still shared as "Anyone with the link can view"?`);
  }
  const csvText = await res.text();
  const { data, errors } = Papa.parse<SheetRow>(csvText, { header: true, skipEmptyLines: true });
  if (errors.length) {
    throw new Error(`Failed to parse the sheet CSV: ${errors[0].message} (row ${errors[0].row})`);
  }
  return data;
}

function buildProducts(rows: SheetRow[]): { products: Product[]; warnings: string[] } {
  const products: Product[] = [];
  const warnings: string[] = [];

  rows.forEach((row, i) => {
    const rowNum = i + 2; // header is row 1, data starts at row 2 in the sheet
    const name = (row['Tên'] || '').trim();
    const summary = (row['Tóm tắt công dụng'] || '').trim();
    const image = (row['Image'] || '').trim();
    const affiliateLink = (row['Affiliate link'] || '').trim();
    const placementRaw = (row['Vị trí hiển thị'] || '').trim();
    const placement = PLACEMENT_MAP[placementRaw];

    const label = name ? `"${name.slice(0, 50)}${name.length > 50 ? '...' : ''}"` : `(row ${rowNum}, no name)`;

    if (!name || !image || !affiliateLink) {
      warnings.push(`Row ${rowNum} ${label}: missing Tên/Image/Affiliate link — skipped`);
      return;
    }
    if (!placement) {
      warnings.push(`Row ${rowNum} ${label}: "Vị trí hiển thị" is "${placementRaw}", expected "Gieo quẻ" / "Kết quả" / "Cả hai" — skipped`);
      return;
    }

    const imageFsPath = path.join(process.cwd(), 'public', image.replace(/^\//, ''));
    if (!fs.existsSync(imageFsPath)) {
      warnings.push(`Row ${rowNum} ${label}: image file not found at public${image} — skipped. Drop the file in public/products/ first.`);
      return;
    }

    products.push({ name, summary: summary || undefined, image, affiliateLink, placement });
  });

  return { products, warnings };
}

function serializeProduct(p: Product): string {
  const lines = [`    name: ${JSON.stringify(p.name)},`];
  if (p.summary) lines.push(`    summary: ${JSON.stringify(p.summary)},`);
  lines.push(`    image: ${JSON.stringify(p.image)},`);
  lines.push(`    affiliateLink: ${JSON.stringify(p.affiliateLink)},`);
  lines.push(`    placement: ${JSON.stringify(p.placement)},`);
  return `  {\n${lines.join('\n')}\n  },`;
}

function generateFileContent(products: Product[]): string {
  return `export type ProductPlacement = 'tossing' | 'result' | 'both';

export interface Product {
  name: string;
  summary?: string;
  image: string;
  affiliateLink: string;
  placement: ProductPlacement;
}

// Auto-generated by \`npm run sync:products\` from the product Google Sheet — do not hand-edit,
// your changes will be overwritten on the next sync. Edit the Sheet instead.
// "Vị trí hiển thị" column: Gieo quẻ -> tossing, Kết quả -> result, Cả hai -> both.
export const PRODUCTS: Product[] = [
${products.map(serializeProduct).join('\n')}
];

export const getProductsForPlacement = (placement: 'tossing' | 'result'): Product[] =>
  PRODUCTS.filter(p => p.placement === placement || p.placement === 'both');
`;
}

async function main() {
  console.log('Fetching product Sheet...');
  const rows = await fetchSheetRows();

  const { products, warnings } = buildProducts(rows);

  if (warnings.length) {
    console.warn('\n⚠ Sync warnings:');
    warnings.forEach(w => console.warn('  - ' + w));
  }

  if (products.length === 0) {
    console.error('\n✗ No valid products found — refusing to overwrite data/products.ts with an empty list.');
    process.exit(1);
  }

  const outPath = path.join(process.cwd(), 'data', 'products.ts');
  fs.writeFileSync(outPath, generateFileContent(products));

  const counts = products.reduce<Record<string, number>>((acc, p) => {
    acc[p.placement] = (acc[p.placement] || 0) + 1;
    return acc;
  }, {});
  console.log(`\n✓ Synced ${products.length} product(s) to data/products.ts (${JSON.stringify(counts)})`);
  console.log('  Remember: commit + push (and redeploy) to make this live.');
}

main().catch((err) => {
  console.error('\n✗ Sync failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
